### ISSUE TITLE
Dialyzer Errors in v2

### ISSUE THREAD

**Issue by maennchen** [kipcole9/cldr#104] opened 2019-01-23 10:02 UTC
Let me first thank you for the great library!

I have upgraded my CLDR dependencies to the newest major release. Now I have a lot of Dialyzer Errors:

```
$ mix dialyzer --halt-exit-status
Finding suitable PLTs
Checking PLT...
[:asn1, :certifi, :cldr_utils, :compiler, :connection, :cowboy, :cowlib, :crypto, :csv, :db_connection, :decimal, :ecto, :ecto_enum, :ecto_sql, :eex, :elixir, :ex_cldr, :ex_cldr_currencies, :ex_cldr_numbers, :file_system, :flow, :gen_stage, :gettext, :hackney, :html_sanitize_ex, :idna, :inets, :jason, :kernel, :logger, :mariaex, :metrics, :mime, :mimerl, :mochiweb, :nimble_parsec, :oauth2, :parallel_stream, :phoenix, :phoenix_active_link, :phoenix_ecto, :phoenix_html, :phoenix_live_reload, :phoenix_pubsub, :plug, :plug_cowboy, :plug_crypto, :public_key, :ranch, :runtime_tools, ...]
PLT is up to date!
Starting Dialyzer
[
  check_plt: false,
  init_plt: '/acme/_build/dev/dialyxir_erlang-21.2.3_elixir-1.8.0_deps-dev.plt',
  files_rec: ['/acme/_build/dev/lib/acme_web/ebin',
   '/acme/_build/dev/lib/acme/ebin'],
  warnings: [:unknown]
]
:0:unknown_type
Unknown type: Cldr.Locale.name/0.
________________________________________________________________________________
:0:unknown_type
Unknown type: List.t/0.
________________________________________________________________________________
:0:unknown_type
Unknown type: Map.t/0.
________________________________________________________________________________
:0:unknown_type
Unknown type: Math.number/0.
________________________________________________________________________________
:0:unknown_type
Unknown type: AcmeWeb.Cldr.Locale.locale_name/0.
________________________________________________________________________________
:0:unknown_type
Unknown type: AcmeWeb.Cldr.Locale.name/0.
________________________________________________________________________________
:0:unknown_type
Unknown type: System.name/0.
________________________________________________________________________________
apps/acme_web/lib/screen24_sales_provision_web/cldr.ex:1:invalid_contract
Invalid type specification for function.

Function:
AcmeWeb.Cldr.validate_locale/1

Success typing:
@spec validate_locale(binary() | %Cldr.LanguageTag{_ => _}) ::
  {:error, {Cldr.UnknownLocaleError, <<_::64, _::size(8)>>}}
  | {:ok, %Cldr.LanguageTag{_ => _}}
________________________________________________________________________________
apps/acme_web/lib/screen24_sales_provision_web/cldr.ex:1:invalid_contract
Invalid type specification for function.

Function:
AcmeWeb.Cldr.Currency.currency_for_code/2

Success typing:
@spec currency_for_code(binary(), Keyword.t()) ::
  {:error, {%{:__exception__ => true, :__struct__ => atom(), atom() => _}, binary()}}
  | {:ok,
     %Cldr.Currency{
       :cash_digits => non_neg_integer(),
       :cash_rounding => non_neg_integer(),
       :code => binary(),
       :count => %{},
       :digits => non_neg_integer(),
       :iso_digits => non_neg_integer(),
       :name => binary(),
       :narrow_symbol => binary(),
       :rounding => non_neg_integer(),
       :symbol => binary(),
       :tender => boolean()
     }}
________________________________________________________________________________
apps/acme_web/lib/screen24_sales_provision_web/cldr.ex:1:invalid_contract
Invalid type specification for function.

Function:
AcmeWeb.Cldr.Currency.new/2

Success typing:
@spec new(_, _) ::
  {:error,
   {Cldr.CurrencyAlreadyDefined, <<_::64, _::size(8)>>}
   | {Cldr.UnknownCurrencyError, <<_::64, _::size(8)>>}}
  | {:ok, %{:__struct__ => atom(), atom() => _}}
________________________________________________________________________________
apps/acme_web/lib/screen24_sales_provision_web/cldr.ex:1:invalid_contract
Invalid type specification for function.

Function:
AcmeWeb.Cldr.Number.to_range_string/2

Success typing:
@spec to_range_string(%Range{:first => _, :last => _, _ => _}, Keyword.t() | map()) :: any()
________________________________________________________________________________
apps/acme_web/lib/screen24_sales_provision_web/cldr.ex:1:invalid_contract
Invalid type specification for function.

Function:
AcmeWeb.Cldr.Number.Format.all_formats_for/1

Success typing:
@spec all_formats_for(binary() | %Cldr.LanguageTag{:cldr_locale_name => <<_::16, _::size(16)>>, _ => _}) ::
  {:error, {Cldr.UnknownLocaleError, <<_::64, _::size(8)>>}} | {:ok, %{:latn => map()}}
________________________________________________________________________________
apps/acme_web/lib/screen24_sales_provision_web/cldr.ex:1:invalid_contract
Invalid type specification for function.

Function:
AcmeWeb.Cldr.Number.Format.all_formats_for!/1

Success typing:
@spec all_formats_for!(binary() | %Cldr.LanguageTag{:cldr_locale_name => <<_::16, _::size(16)>>, _ => _}) :: %{
  :latn => map()
}
________________________________________________________________________________
apps/acme_web/lib/screen24_sales_provision_web/cldr.ex:1:invalid_contract
Invalid type specification for function.

Function:
AcmeWeb.Cldr.Number.Symbol.number_symbols_for/1

Success typing:
@spec number_symbols_for(binary() | %Cldr.LanguageTag{:cldr_locale_name => nil | binary(), _ => _}) ::
  {:error, {Cldr.UnknownLocaleError, <<_::64, _::size(8)>>}} | {:ok, %{:latn => map()}}
________________________________________________________________________________
apps/acme_web/lib/screen24_sales_provision_web/cldr.ex:1:invalid_contract
Invalid type specification for function.

Function:
AcmeWeb.Cldr.Number.System.number_system_names_for/1

Success typing:
@spec number_system_names_for(binary() | %Cldr.LanguageTag{:cldr_locale_name => nil | binary(), _ => _}) ::
  {:error, {Cldr.UnknownLocaleError, <<_::64, _::size(8)>>}} | {:ok, [any()]}
________________________________________________________________________________
lib/backend/format.ex:249:pattern_match
The pattern
{:error, {_, _}}

can never match the type
{:ok, 1}
________________________________________________________________________________
lib/backend/transliterate.ex:1:no_return
Function transliterate/1 has no local return.
________________________________________________________________________________
lib/backend/transliterate.ex:1:no_return
Function transliterate/2 has no local return.
________________________________________________________________________________
lib/backend/transliterate.ex:107:call
The call:
AcmeWeb.Cldr.Number.Transliterate.transliterate(
  _ :: any(),
  %Cldr.LanguageTag{
    :canonical_locale_name => binary(),
    :cldr_locale_name => nil | binary(),
    :extensions => %{},
    :gettext_locale_name => _,
    :language => binary(),
    :language_subtags => [binary()],
    :language_variant => nil | binary(),
    :locale => %{},
    :private_use => [binary()],
    :rbnf_locale_name => binary(),
    :requested_locale_name => binary(),
    :script => nil | binary(),
    :territory => nil | binary(),
    :transform => %{}
  },
  :default
)

breaks the contract
(String.t(), Cldr.LanguageTag.t(), String.t()) :: String.t()
________________________________________________________________________________
lib/backend/transliterate.ex:108:call
The call:
AcmeWeb.Cldr.Number.Transliterate.transliterate(_ :: any(), _ :: any(), :default)

breaks the contract
(String.t(), Cldr.LanguageTag.t(), String.t()) :: String.t()
________________________________________________________________________________
lib/backend/transliterate.ex:150:pattern_match
The pattern
{:error, {_, _}}

can never match the type
binary()
________________________________________________________________________________
lib/cldr/backend.ex:1:no_return
Function known_currency?/1 has no local return.
________________________________________________________________________________
lib/cldr/backend.ex:153:call
The call:
AcmeWeb.Cldr.Currency.known_currency?(_ :: any(), [])

will never return since the success typing is:
(binary(), [
  %Cldr.Currency{
    :cash_digits => non_neg_integer(),
    :cash_rounding => non_neg_integer(),
    :code => binary(),
    :count => %{},
    :digits => non_neg_integer(),
    :iso_digits => non_neg_integer(),
    :name => binary(),
    :narrow_symbol => binary(),
    :rounding => non_neg_integer(),
    :symbol => binary(),
    :tender => boolean()
  },
  ...
]) :: boolean()

and the contract is
(Cldr.Currency.code(), [Cldr.Currency.t(), ...]) :: boolean()
________________________________________________________________________________
Total errors: 23, Skipped: 0
done in 0m13.91s
done (warnings were emitted)
```

**Comment by kipcole9** [comment] 2019-01-23 13:08
I have such a love/hate relationship with dialyzer.  Mostly it hates me.  :-)  But I appreciate the report and will do my best to fix the typespecs and publish an update.

**Comment by maennchen** [comment] 2019-01-23 15:55
@kipcole9 I feel the same about it, always a hassle to maintain. It found me some pretty hard to find bugs though.

Thanks for your efforts!

**Comment by kipcole9** [comment] 2019-02-10 06:56
OK, I'm on it.  The new dialyxir helps, but a few things - especially in nimble_parsec combinators seem unsolvable by me.  Anyway, I'll keep plugging away.

**Comment by kipcole9** [comment] 2019-02-10 11:00
Except for nimble_parsec errors, dialyzer is now happy.  I'll work on a PR for nimble_parsec this evening.

**Comment by kipcole9** [comment] 2019-03-10 18:14
All dialyzer warnings are now fixed or silienced in ex_cldr version 2.4.0

**Closed by kipcole9** 2019-03-10 18:14 UTC

**Comment by maennchen** [comment] 2020-01-13 17:05
@kipcole9 I found a new one again:

```
lib/cldr/backend/formatter.ex:1: The pattern <#{'number_system':=__@1}, __@2> can never match the type <<<_:8,_:_*8>>,_>
```

It also seems to trip dialyzer, opened an issue here: https://github.com/jeremyjh/dialyxir/issues/380

**Comment by kipcole9** [comment] 2020-01-13 18:47
Thats .... surprising. And on a fresh run of dialyzer (Elixir 1.10.0-rc.0, Erlang 22.2) I don't see this error. I'll look into it though.

**Comment by kipcole9** [comment] 2020-01-13 19:54
I've rerun dialyzer on `ex_cldr`, `ex_cldr_numbers` and `ex_cldr_dates_times` and none of them generate this (or any) dialyzer error for me. I did clean up one outstanding dialyzer warning in `ex_cldr` but it is unrelated to this issue. Any thoughts on how to progress on this?

**Comment by maennchen** [comment] 2020-01-14 08:33
@kipcole9 Sorry, this should be reported in the date time cldr library. The error happens only if that one is used.

**Comment by maennchen** [comment] 2020-01-14 08:35
We basically only use two calls for date / time in our project:

* `Cldr.Date.to_string!(start_date, Acme.Cldr, format: "MM.yyyy")`
* `@creation_date |> DateTime.to_date() |> Cldr.Date.to_string!(Acme.Cldr)`

**Comment by kipcole9** [comment] 2020-01-14 08:48
Thanks for the extra data. I'll try to reproduce in a client application - there aren't any dialyzer warnings when I run it against the lib itself.

**Comment by kipcole9** [comment] 2020-01-14 09:42
OK, I was able to work out what the issue was in the generated backend code and the fix is in [ex_cldr_dates_times version 2.2.4](https://hex.pm/packages/ex_cldr_dates_times/2.2.4).

Making dialyzer happy with generated code is just even more "fun" on top of the usual dialyzer enjoyment. :-)

**Comment by maennchen** [comment] 2020-01-14 09:48
@kipcole9 Thank you very much! I‘ll give it a try 😊

**Comment by kipcole9** [comment] 2020-01-14 09:56
You've pushed me to wrap my head around dialyzer and even though I'm not totally convinced it has so far helped my identify 4 bugs across all my libs. But ... the learning curve is steep!!!! The newer versions of dialixir really help because of its message formatting.

**Comment by maennchen** [comment] 2020-01-14 10:33
I tried it and this solves my issue :)

I found quite a lot of bugs using dialyzer. It helped me a lot. It's however also a pain in the ass often with very cryptic errors or no reasons on how it found an error.
