### ISSUE TITLE
Plug Warning

### ISSUE THREAD

**Issue by maennchen** [kipcole9/cldr#92] opened 2018-11-23 15:20 UTC
If the `Cldr.Plug.AcceptLanguage` plug is used, a warning is logged.

Endpoint Code:

```elixir
defmodule Acme.Endpoint do
  use Phoenix.Endpoint, otp_app: :acme

  # ...

  plug(Cldr.Plug.AcceptLanguage)

  # ...
end
```

Log:

```
16:16:24.920 [warn]  Elixir.Cldr.Plug.AcceptLanguage does not support configuration options. Please remove [] from the plug invokation.
```

Library Versions:

* `phoenix` - `1.4.0`
* `plug` - `1.7.1`
* `ex_cldr` - `1.8.1`

**Comment by kipcole9** [comment] 2018-11-23 15:32
@maennchen Thanks for the report.  Its unexpected behaviour and moving to version 2.0, although a good idea, isn't ready if you need dates and times (as you observed).

I'll work out why the issue and fix it in version 1.8x.  Sorry for the inconvenience.

### Expectations
* 24 hours fix for this issue in the 1.8 branch
* 2 weeks for `ex_cldr_dates_times` and `cldr_units`
* 2 days for `ex_cldr_lists`

**Comment by kipcole9** [comment] 2018-11-23 16:06
It was a quick fix.  Turns out endpoint plugs get passed an empty list `[]` for params.  This no longer logs a warning in [ex_cldr version 1.8.2](https://hex.pm/packages/ex_cldr/1.8.2) just released on hex. Code and tests updated.

**Closed by kipcole9** 2018-11-23 16:06 UTC

**Comment by kipcole9** [comment] 2018-11-23 16:16
By the way, in version 2.0 a `cldr_backend: <module_name>` is a required option.

**Comment by maennchen** [comment] 2018-11-23 16:34
@kipcole9 Thanks for the quick fix! I'll update right away.

**Comment by maennchen** [comment] 2018-11-23 16:43
Seems to work, thank you again!
