### ISSUE TITLE
Cldr.DateTime.to_string seems extremely slow

### ISSUE THREAD

**Issue by marceldegraaf** [kipcole9/cldr#43] opened 2018-02-06 09:59 UTC
Today we noticed that a specific page in our production Elixir/Phoenix application would load much slower than expected, sometimes taking 5+ seconds to load completely. Initially we suspected slow Javascript load times, but local debugging led us to this call in one of our view helpers:

```
Cldr.DateTime.to_string(payment.inserted_at, format: :medium, locale: "nl")
```

Where `payment.inserted_at` is a UTC DateTime from a database table, retrieved with Ecto. I ran a profile of this specific function with `ex_prof` on a list of 25 payment records:

```
import ExProf.Macro

profile do
  Enum.map(payments, fn(payment) ->
    Cldr.DateTime.to_string(payment.inserted_at, format: :medium, locale: "nl")
  end)
end
```

The full results [are here](https://gist.github.com/marceldegraaf/ecdbcbcf97e44483baf0480681c382b8).

Benchmarking the same call with Benchee shows that the 99th% takes 2.13s:

```
Benchee.run(%{ "ex_cldr" => fn -> Enum.map(payments, fn(payment) -> Cldr.DateTime.to_string(payment.inserted_at, format: :medium, locale: "nl") end) end })
Operating System: macOS
CPU Information: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
Number of Available Cores: 4
Available memory: 16 GB
Elixir 1.6.0
Erlang 20.2.2
Benchmark suite executing with the following configuration:
warmup: 2 s
time: 5 s
parallel: 1
inputs: none specified
Estimated total run time: 7 s


Benchmarking ex_cldr...

Name              ips        average  deviation         median         99th %
ex_cldr          0.49         2.05 s     ±4.17%         2.09 s         2.13 s
```

This is our configuration for `ex_cldr`:

```
config :ex_cldr,
       default_locale: "en",
       locales: ["en", "nl"],
       gettext: MyApp.Web.Gettext
```

Are we missing something in our configuration or is this an actual issue in ExCldr?

**Comment by marceldegraaf** [comment] 2018-02-06 10:54
Update: this seems to occur only on version 1.4.0 of `ex_cldr`. If I revert to version 1.3.0, the issue disappears. Let me know if you need more information to help you pin point the issue.

**Comment by kipcole9** [comment] 2018-02-06 12:53
I apologise for the regression. 

It’s not obvious to me how that crept into the release since no formatting code was touched.  

I won’t be able to resolve during the rest of your day.  But since I’m in ask galore I should have a resolution by the time you start again in the morning.

**Comment by marceldegraaf** [comment] 2018-02-06 12:54
Awesome, no worries, we're fine on 1.3.0 now. Do let me know if we can help you with any additional debug/profile info.

**Comment by kipcole9** [comment] 2018-02-07 07:36
First of all, thank you very much for the very helpful support to isolate the issue.  I configured the machine I'm on (a very modest original MacBook from 2015).
```
config :ex_cldr,
  default_locale: "en",
  locales: ["en", "nl"],
  gettext: GettextModule
```
I ran your benchmark function with and without the `GettextModule` configured.  Gettext itself is configured with "en" and "nl" on the assumption that is what you are using.

For the benchmark I just used `DateTime.utc_now/0` which I think is unlikely to be the variance. I ran on Elixir 1.6.1 and 1.7.0-dev and the results were basically the same.

### _Without_ Gettext configured in ex_cldr:
```
Name              ips        average  deviation         median         99th %
ex_cldr        3.91 K      255.63 μs    ±25.85%         237 μs         478 μs
```

### _With_ Gettext configured in `ex_cldr`:
```
Name              ips        average  deviation         median         99th %
ex_cldr        1.67 K      598.26 μs    ±20.41%         548 μs     1052.56 μs
```
So without `GettextModule` the result look about what I would expect (I know I need to build some regression tests as part of the release process).  Very surprising the results look totally unacceptable when `GettextModule` is configured.  Nearly three times the execution time.

`ex_cldr` 1.4 definitely has some commits in the Gettext area - but only supposed to be related to configuration.  Clearly thats not so.

I need to keep digging but I wanted to keep you up-to-date and to see if this would appear consistent with your own observations?

**Comment by kipcole9** [comment] 2018-02-07 07:54
One thing I notice is that you are using `locale: "nl"`, meaning a binary locale name.  Under the covers all locale names are parsed into a `%Cldr.LanguageTag{}` struct which is quite costly.  I ran your benchmark both using a binary locale name and a `%Cldr.LanguageTag{}`.  The difference is quite dramatic which is what I expected:
```
iex> {:ok, nl} = Cldr.validate_locale "nl"
{:ok,
 %Cldr.LanguageTag{
   canonical_locale_name: "nl-Latn-NL",
   cldr_locale_name: "nl",
   extensions: %{},
   gettext_locale_name: "nl",
   language: "nl",
   locale: %{},
   private_use: [],
   rbnf_locale_name: "nl",
   requested_locale_name: "nl",
   script: "Latn",
   territory: "NL",
   transform: %{},
   variant: nil
 }}
iex> Benchee.run(%{ 
..."parsed_locale" => fn -> Cldr.DateTime.to_string(DateTime.utc_now, format: :medium, locale: nl) end,   
..."string locale" => fn -> Cldr.DateTime.to_string(DateTime.utc_now, format: :medium, locale: "nl") end
})

Name                    ips        average  deviation         median         99th %
parsed_locale       34.89 K       28.66 μs    ±72.76%          25 μs          60 μs
string locale        1.58 K      633.07 μs    ±22.39%         581 μs     1182.66 μs
```
Therefore I have two actions to take from this investigation:

1. Make the documentation a lot clearer on the implications of using binary locale names
2. Precompile the language tags of the configured locales which optimise the use of configured binary locales to be basically the same as the compiled ones.

This is not actually the regressions as far as I can see but it is an important design and optimisation note.

Work continues.

**Comment by marceldegraaf** [comment] 2018-02-07 08:30
Thanks for your investigation and detailed comments. I've tried both your recommendations; here are my results.

### Without `gettext` module in configuration
This seems to reduce the median operation time significantly. Strangely my results are consistently lower than yours. Where your median operation time is around 500 µs, mine is just under 2ms. However, it's much better than the 2**s** in the initial report.

```
Benchee.run(%{"cldr" => fn -> Enum.map(users, fn(user) -> Cldr.Date.to_string(user.inserted_at, format: :medium, locale: "en") end) end})

Name           ips        average  deviation         median         99th %
cldr        556.19        1.80 ms     ±6.38%        1.77 ms        2.18 ms
```

### Using a parsed `locale`
While my numbers are consistently higher than yours, my findings are consistent: using a parsed locale is around 5.000x faster than using a string locale:

```
Name                    ips        average  deviation         median         99th %
parsed locale       58.52 K      0.0171 ms   ±100.95%      0.0150 ms      0.0440 ms
string locale      0.0118 K       84.67 ms     ±3.35%       84.44 ms       95.79 ms

Comparison:
parsed locale       58.52 K
string locale      0.0118 K - 4954.86x slower
```

It seems like a good idea for us to use the parsed locales in our code. What would be the recommended way to do this? If we compile the locale from the string version each time we call Cldr I suppose we get the same performance penalty; should we somehow precompile those parsed locales when our application starts?

**Comment by kipcole9** [comment] 2018-02-07 09:02
Curious to me that the magnitude of performance difference between this old slow MacBook from 2015 is so different to your machine but happy that the improvement is material.'

For the short term the approach I suggest is the following:

### Create a module like this:
```elixir
defmodule My.Locale do
  for locale_name <- Cldr.Config.known_locale_names do
    language_tag = Cldr.Locale.new!(locale_name)
    # Create a function for each configured
    # locale name that returns the parsed version
    def locale(unquote(locale_name)) do
      unquote(Macro.escape(language_tag))
    end
  end

  def locale(other) when is_binary(other) do
    other
  end
end
```
### In your view code:
```
Cldr.Date.to_string(user.inserted_at, format: :medium, locale: My.Locale.locale("en")
```
This will avoid the parsing issue.  I will put this code into Cldr such that it will automatically be done without user code.  I'm aiming to get that done in the next 12 hours but it may take up to 24.

This still isn't the regression you were originally seeing but it does get performance back under control.  

Next step is to integrate this into `Cldr` and release version 1.4.1 as soon as possible.

**Comment by kipcole9** [comment] 2018-02-07 14:59
I have [added a commit to the Cldr master branch](https://github.com/kipcole9/cldr/commit/1578fc43ec862bd1c4ab997ec6a2ff1743e91db3) that pre-computes the language tags for all Cldr locales and therefore the performance for binary locale names and for language tags is now the same.
```
Name                    ips        average  deviation         median         99th %
parsed locale       36.54 K       27.37 μs    ±54.40%          25 μs          60 μs
string locale       35.32 K       28.31 μs    ±54.70%          25 μs          63 μs
```
All tests are passing and this is close to releasable as Cldr version 1.4.1 but I have one issue related to resolving the struct field `:gettext_locale_name` which can't be pre-generated for obvious reasons. When I resolve that issue I'll re-publish to hex.

**Comment by kipcole9** [comment] 2018-02-08 09:04
I have [pushed ex_cldr version 1.4.1](https://hex.pm/packages/ex_cldr/1.4.1) to hex.  Thanks very much for your collaboration and patience.

### Performance on 1.4.1

I ran the formatting test again with the following results using this version:

```elixir
iex> Benchee.run(%{                                                                                    
...>   "parsed" => fn -> Cldr.DateTime.to_string(DateTime.utc_now, format: :medium, locale: nl) end,   
...>   "binary" => fn -> Cldr.DateTime.to_string(DateTime.utc_now, format: :medium, locale: "nl") end})

Name             ips        average  deviation         median         99th %
parsed       34.55 K       28.94 μs    ±47.43%          25 μs          71 μs
binary       33.56 K       29.80 μs    ±76.12%          26 μs          69 μs
```
I'm leaving the issue open for now because I'm not totally convinced this was the root cause since the behaviour would have been the same between versions 1.3 and 1.4 but I am optimistic this gets the performance back at the level you would expect and, I hope, be good enough for you to move back to the 1.4 version series.

A simple `mix deps.update ex_cldr` should do it if you relax your version requirements back to `{:ex_cldr, "~> 1.0"}`.

### Changelog for Cldr v1.4.1

This is the changelog for Cldr v1.4.1 released on February 8th, 2018.  For older changelogs please consult the release tag on [GitHub](https://github.com/kipcole9/cldr/tags)

As reported by @marceldegraaf there has been a regression in the performance of `Cldr.DateTime.to_string/2`.  The use case he reported involved calls with `locale: "nl"`; ie using a binary `:locale`.

In all cases, locale resolution is passed through `Cldr.validate_locale/1`.  In prior releases of `Cldr` this would require parsing the locale name which is a relatively expensive operation.

Therefore the major focus on this small release is to pre-parse all configured locale names into their corresponding language tag.  As a result performance is largely the same whether locale is specified as a binary or as a language tag.

## Enhancements

* Precompiles all known locale names into a language tag which are then used to generate locale specific versions of `Cldr.validate_locale/1` when the parameter is a binary.

* Adds a mix task (available in github, not in the hex package) to generate the language tags for all available locales to support the performance optimization of locale to langauge tag lookup which is used in `Cldr.validate_locale/1` in many places in `Cldr`.

* Automatically detects the presence of `Jason` and `Poison` and configures the default `:json_library` appropriately.

**Comment by marceldegraaf** [comment] 2018-02-08 13:17
This is amazing. I've just installed `1.4.1` and can confirm it's working fast as usual again. Thank you so much for your swift and detailed responses and for pushing out this release so fast. Truly remarkable.

Cheers! 🍻

**Comment by kipcole9** [comment] 2018-02-08 14:42
You're very welcome.  I think José and team set a high standard for good code and I just try to keep up 😄  Keep the bugs and suggestions coming! 

I'll do some profiling of the code over the weekend and see if I can find what might have been the issue you saw that started this issue.

**Closed** 2018-04-09 15:26 UTC
